Flipkart_Security/Flipkart_Security/urls.py
from django.contrib import admin
from django.urls import path, include
from landingPage.views import landing_page


urlpatterns = [
    path('', landing_page, name="landing_page"),
    path('input/', include('inputPage.urls')),
]

Flipkart_Security/inputPage/urls.py
from django.urls import path
from . import views

app_name = 'input'

urlpatterns = [
    path('input/', views.input_view, name='input_view'),
    path('get text', views.form_view, name='text_view'),
    # path('save-text/', views.save_text, name='save_text'),
    path('/button_quick', views.button_quick, name='button_quick'),
    path('/button_full', views.button_full, name='button_full'),
    path('uploadForm/', views.form_view, name='form_view')
]

Flipkart_Security/inputPage/models.py
from django.db import models
class data_file(models.Model):
    file1=models.FileField(upload_to="inputPage/SOURCE_DOCUMENTS/")
# Create your models here.

Flipkart_Security/landingPage/models.py
from django.db import models

# Create your models here.

Flipkart_Security/inputPage/forms.py
from django import forms
from inputPage.models import data_file
class UploadFileForm(forms.ModelForm):
    class Meta:
        model = data_file
        fields=('file1',)

Flipkart_Security/inputPage/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import data_file
from .forms import UploadFileForm
import inputPage.quick_search as qs
import inputPage.full_search as fs
import inputPage.ingest as ingester


# Create your views here.
# def save_text(request):
#     global saved_text
#     if request.method == "POST":
#         data = request.POST
#         saved_text = data.get("text", "")
#         print(saved_text)
#         return JsonResponse({"message": "Text saved successfully."})


def form_view(request):
    print(16)
    if request.method == 'POST':
        print(3)
        fileList = request.FILES.getlist("upload_form")
        for file in fileList:
            fileSave = data_file.objects.create(file1=file)
            # print(form)
            fileSave.save()

            print("file saved: " + fileSave.file1.path)

        # print(str(form))
        # if form.is_valid():
        #     form.save()
        #     print(1)
        # qs.get_result("""NO ONE SHOULD HAVE role: roles/owner
        #      NO ONE SHOULD HAVE role: roles/editor
        #      NO ONE SHOULD HAVE role: roles/owner""")
    # context = {'form':data_file()}
    print(str(request.POST))
    ruleStr = request.POST.get('rules')
    print(ruleStr)
    # ingester.runs()
    result_dict = fs.main(ruleStr)
    output_text = result_dict.get('output_text', '').strip()
    print('-'*34)
    print(output_text)
    context = {
        'output': output_text
    }
    return render(request, 'inputPage/input.html', context)


def button_full(request):
    fs.get_result()


#
def button_quick(request):
    pass


def input_view(request):
    return render(request, 'inputPage/input.html')

Flipkart_Security/landingPage/views.py
from django.shortcuts import render


def landing_page(request):
    return render(request, 'landingPage/landing.html')

Flipkart_Security/inputPage/templates/inputPage/input.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Guardian</title>
    {% load static %}
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;700&display=swap"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Sharp:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Orbitron&display=swap"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
      integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Sharp"
      rel="stylesheet"
    />
    <link href="{% static 'inputPage/input.css' %}" rel="stylesheet" />
  </head>
  <body>
    <header id="header">
      <h1 class="logo"><a href="landing.html">Guardian</a></h1>
      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto" href="#landing.html">Home</a></li>
        </ul>
      </nav>
    </header>
    <div class="container">
      <div class="left-content">
        <form
          method="post"
          enctype="multipart/form-data"
          action="{% url 'input:form_view' %}"
        >
          <div class="content-box">
            <div class="text-box">
              <h2 class="text-heading">Paste the rules</h2>
              <textarea
                class="text-input"
                id="rules"
                name="rules"
                placeholder="Enter your text here"
              ></textarea>
            </div>
            <div class="drag-area">
              <input
                type="file"
                name="upload_form"
                multiple
                class="input-file"
              />
              {% csrf_token %}
              <input
                type="submit"
                value="submit"
                name="upload_form"
                class="input-submit"
              />
            </div>
          </div>
        </form>
      </div>

      <div class="right-content">
        <h2 class="text-heading">Output</h2>
        <textarea class="text-output" placeholder="Your output will be here">
{{ output }}</textarea
        >
      </div>
    </div>
  </body>
</html>

Flipkart_Security/landingPage/templates/landingPage/landing.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Guardian</title>

    {% load static %}

<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;700&display=swap">
<link
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Sharp:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
    rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Orbitron&display=swap">

<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Sharp" rel="stylesheet" />
<link href="{% static 'landingPage/landing.css' %}" rel="stylesheet">
</head>

<body>
    <header id="header">
        <h1 class="logo"><a href="landing.html">Guardian</a></h1>
        <nav id="navbar" class="navbar">
            <ul>
                <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
                <li><a class="nav-link scrollto" href="#features">Features</a></li>
                <li><a class="nav-link scrollto" href="#team">Our Team</a></li>
            </ul>
        </nav>
    </header>
    <section id="hero">
        <div class="container text-left">
            <h1 class="hero-title">Unlocking Compliance Confidence<br>
                Through Advanced Log Analysis with LLM.</h1>
            <h3 class="hero-subtitle">Are you facing the challenge of ensuring robust security compliance in the
                ever-evolving landscape of data and systems? Introducing a groundbreaking solution that revolutionizes
                compliance monitoring and enforcement.</h3>
            <div class="btn-container">
                <a href="{% url 'input:input_view' %}" class="btn-get-started scrollto">Get Started</a>
            </div>
        </div>
        <div class="hero-svg">
            <div class="svg-container">
                <img src="https://res.cloudinary.com/dhhax6yae/image/upload/v1691766491/undraw_security_on_re_e491_1_iwqzp7.svg"
                    class="svg-right" />
            </div>
        </div>
    </section>
    <main id="main">
        <section id="features" class="features">
            <div class="row">
                <h1>Our Features</h1>
            </div>
            <div class="row">
                <div class="column">
                    <div class="feature-card">
                        <div class="icon">
                            <span class="material-symbols-sharp">
                                monitoring
                                </span>
                        </div>
                        <h3>Rule Inference & Analysis</h3>
                        <p>
                            Effortlessly interpret and deduce connections between provided rules and parameters within
                            logs and policies. Our system intelligently distills complex rule relationships, enhancing
                            compliance monitoring accuracy.
                        </p>
                    </div>
                </div>

                <div class="column">
                    <div class="feature-card">
                        <div class="icon">
                            <span class="material-symbols-sharp">
                                file_copy
                                </span>
                        </div>
                        <h3>Format Agnostic Adaptability</h3>
                        <p>
                            Adapts seamlessly to diverse log formats - CSV, text, PDF - and an array of compliance
                            standards. Our solution effortlessly fits into various environments and configurations,
                            ensuring your unique needs are met.
                        </p>
                    </div>
                </div>

                <div class="column">
                    <div class="feature-card">
                        <div class="icon">
                            <span class="material-symbols-sharp">
                                data_exploration
                                </span>
                        </div>
                        <h3>Actionable Remediation Insights</h3>
                        <p>
                            Empowers you with practical, valuable insights for remediation. Our system doesn't just
                            detect compliance breaches; it guides you with actionable recommendations to efficiently
                            address security vulnerabilities.
                        </p>
                    </div>
                </div>
            </div>
            <section id="team" class="team">
                <div class="row">
                  <h1>Our Team</h1>
                </div>
                <div class="row">
     
                  <div class="column">
                    <div class="team-card">
                      <div class="img-container">
                        <img src="https://res.cloudinary.com/dhhax6yae/image/upload/v1691769477/Gouravv_blqkzd.png" />
                      </div>
                      <h3>Gourav Mohanty</h3>
                      <p>Full-Stack Developer</p>
                    </div>
                  </div>
                  
                  <div class="column">
                    <div class="team-card">
                      <div class="img-container">
                        <img src="https://res.cloudinary.com/dhhax6yae/image/upload/v1691769490/Paneer_qc1zhn.png" />
                      </div>
                      <h3>Sai Praneetha</h3>
                      <p>Front-end Developer & UI/UX Developer </p>
                      </div>
                    </div>
                
                    <div class="column">
                      <div class="team-card">
                        <div class="img-container">
                          <img src="https://res.cloudinary.com/dhhax6yae/image/upload/v1691769479/Pramod_soagk7.png" />
                        </div>
                        <h3>Pramod Goyal</h3>
                        <p>Machine Learning Developer</p>
                      </div>
                    </div>
                  </div>
                </section>
    </main>
</body>

</html>